version: "3.8"

services:
  backend:
    build: ./reddit-clone-backend
    ports:
      - "5000:5000"
    volumes:
      - ./reddit-clone-backend:/app
      - /app/node_modules
    environment:
      - PORT=5000
      - NODE_ENV=development
